import { createContext, useContext } from 'react';

export type Lang = 'zh' | 'en';

const translations: Record<Lang, Record<string, string>> = {
  zh: {
    'app.logo': '多境',
    'app.tagline': '一句话 · 多场景创作',
    'app.footer': '多境 — 你的内容，你的 API Key，数据不出浏览器',
    'app.byok': 'BYOK · v0.1',
    'app.langBtn': 'English',

    'tab.rewrite': '内容改写',
    'tab.voiceover': '场景配音',

    'input.hint.title': '💡 如何使用',
    'input.hint.text': '输入一句话、产品描述或几个要点，AI 会自动为选中的平台生成适配的营销内容。',

    'config.configure': '配置 AI 服务商',
    'config.configured': 'AI 服务商已配置',
    'config.provider': '服务商',
    'config.yunfan.connected': '使用云帆 AI 网关，无需额外配置',
    'config.baseUrl': '接口地址',
    'config.model': '模型',
    'config.apiKey': 'API Key',
    'config.clear': '清除 API Key',
    'config.provider.yunfan': '☁️ 云帆 AI 网关',
    'config.provider.openai': 'OpenAI',
    'config.provider.deepseek': 'DeepSeek',
    'config.provider.custom': '自定义 (OpenAI 兼容)',

    'input.label': '📝 创作内容',
    'input.chars': '字符',
    'input.placeholder': '输入你的创意简报、产品描述、博客文章或关键要点...\n\n示例：我们刚发布了一款AI写作助手...\n\n💡 技巧：\n• 一句话 → AI 生成多平台内容\n• 产品卖点 → 自动适配各平台风格\n• 文章核心 → 提炼并重写为各平台版本',
    'input.cancel': '✕ 取消',
    'input.generate': '✨ 生成多平台内容',
    'input.hint': '⚠️ 请先配置 API Key 即可生成',

    'platform.label': '📤 选择平台',
    'platform.selectAll': '全选',
    'platform.none': '清空',

    'tone.label': '🎭 语气',

    'output.title': '📋 生成结果',
    'output.progress': '⏳ {done}/{total} 个平台',
    'output.download': '⬇ 下载全部 (.md)',
    'output.waiting': '等待中...',
    'output.error': '错误：',
    'output.copied': '✓ 已复制！',
    'output.copy': '📋 复制',
    'output.regenerate': '🔄 重新生成',
    'output.edit': '编辑',
    'output.preview': '预览',
    'output.tweets': '条推文',
    'output.chars': '字符',

    'export.title': '# 多境 — MultiScene 导出',
    'export.generated': '由多境 (MultiScene) 生成',
    'export.filename': '多境-导出',

    'footer.github': 'GitHub',
    'footer.contact': '联系',

    // Tones
    'tone.professional': '专业',
    'tone.casual': '随和',
    'tone.promotional': '促销',
    'tone.storytelling': '讲故事',
    'tone.educational': '教育',

    // Platform labels
    'platform.twitter': 'X / Twitter',
    'platform.linkedin': 'LinkedIn',
    'platform.newsletter': 'Newsletter',
    'platform.wechat': '微信公众平台',
    'platform.xiaohongshu': '小红书',
    'platform.reddit': 'Reddit',

    // Platform descriptions
    'platform.twitter.desc': '推文串格式，吸引眼球的开头',
    'platform.linkedin.desc': '专业调性，叙事风格',
    'platform.newsletter.desc': '完整文章，含主题行',
    'platform.wechat.desc': '中文长文，正式教育调性',
    'platform.xiaohongshu.desc': '视觉化叙述，emoji，经验分享',
    'platform.reddit.desc': '对话风格，社区意识',
  },

  en: {
    'app.logo': 'MultiScene',
    'app.tagline': 'One Thought · Multi-Scene Creation',
    'app.footer': 'MultiScene — your content, your API key, your data never leaves your browser',
    'app.byok': 'BYOK · v0.1',
    'app.langBtn': '中文',

    'tab.rewrite': 'Content Rewrite',
    'tab.voiceover': 'Voiceover',

    'input.hint.title': '💡 How to Use',
    'input.hint.text': 'Drop a brief, product description, or a few bullet points — AI generates platform-optimized content for your selected channels.',

    'config.configure': 'Configure AI Provider',
    'config.configured': 'AI Provider configured',
    'config.provider': 'Provider',
    'config.yunfan.connected': 'Connected to YunFan AI Gateway',
    'config.baseUrl': 'Base URL',
    'config.model': 'Model',
    'config.apiKey': 'API Key',
    'config.clear': 'Clear API Key',
    'config.provider.yunfan': '☁️ YunFan AI Gateway',
    'config.provider.openai': 'OpenAI',
    'config.provider.deepseek': 'DeepSeek',
    'config.provider.custom': 'Custom (OpenAI-compatible)',

    'input.label': '📝 Content Brief',
    'input.chars': 'chars',
    'input.placeholder': 'Enter your creative brief, product description, blog post, or key points...\n\nExample: We just launched an AI writing assistant...\n\n💡 Tips:\n• One-liner → AI creates multi-platform content\n• Product features → Auto-adapt to each platform\n• Article core → Extract and rewrite for each platform',
    'input.cancel': '✕ Cancel',
    'input.generate': '✨ Generate Multi-Platform Content',
    'input.hint': '⚠️ Configure your API Key above to enable generation',

    'platform.label': '📤 Select Platforms',
    'platform.selectAll': 'Select All',
    'platform.none': 'None',

    'tone.label': '🎭 Tone',

    'output.title': '📋 Generated Results',
    'output.progress': '⏳ {done}/{total} platforms',
    'output.download': '⬇ Download All (.md)',
    'output.waiting': 'Waiting...',
    'output.error': 'Error: ',
    'output.copied': '✓ Copied!',
    'output.copy': '📋 Copy',
    'output.regenerate': '🔄 Regenerate',
    'output.edit': 'Edit',
    'output.preview': 'Preview',
    'output.tweets': 'tweets',
    'output.chars': 'chars',

    'export.title': '# MultiScene Export',
    'export.generated': 'Generated by MultiScene',
    'export.filename': 'multiscene-export',

    'footer.github': 'GitHub',
    'footer.contact': 'Contact',

    // Tones
    'tone.professional': 'Professional',
    'tone.casual': 'Casual / Friendly',
    'tone.promotional': 'Promotional / Sales',
    'tone.storytelling': 'Storytelling',
    'tone.educational': 'Educational',

    // Platform labels
    'platform.twitter': 'X / Twitter',
    'platform.linkedin': 'LinkedIn',
    'platform.newsletter': 'Newsletter',
    'platform.wechat': '微信公众平台',
    'platform.xiaohongshu': '小红书',
    'platform.reddit': 'Reddit',

    // Platform descriptions
    'platform.twitter.desc': 'Thread format, punchy hook',
    'platform.linkedin.desc': 'Professional tone, narrative',
    'platform.newsletter.desc': 'Full article with subject line',
    'platform.wechat.desc': '中文长文，正式教育调性',
    'platform.xiaohongshu.desc': '视觉化叙述，emoji，经验分享',
    'platform.reddit.desc': 'Conversational, community-aware',
  },
};

export const LANG_KEY = 'yuzhiran-lang';

export function getStoredLang(): Lang {
  try {
    const stored = localStorage.getItem(LANG_KEY);
    if (stored === 'en' || stored === 'zh') return stored;
  } catch { /* ignore */ }
  return 'zh';
}

export function storeLang(lang: Lang): void {
  try { localStorage.setItem(LANG_KEY, lang); } catch { /* ignore */ }
}

export function t(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  let text = translations[lang]?.[key] ?? translations['zh']?.[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replace(`{${k}}`, String(v));
    }
  }
  return text;
}

export interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const LangContext = createContext<LangContextValue>({
  lang: 'zh',
  setLang: () => {},
});

export function useLang() {
  return useContext(LangContext);
}
