import { createContext, useContext } from 'react';

export type Lang = 'zh' | 'en';

const translations: Record<Lang, Record<string, string>> = {
  zh: {
    'app.logo': '一篇多发',
    'app.tagline': '一次撰写 · 全网发布',
    'app.footer': '一篇多发 — 你的内容，你的 API Key，数据不出浏览器',
    'app.byok': 'BYOK · v0.1',
    'app.langBtn': 'English',

    'config.configured': 'API Key 已配置',
    'config.configure': '配置 AI 服务商',
    'config.provider': '服务商',
    'config.baseUrl': '接口地址',
    'config.model': '模型',
    'config.apiKey': 'API Key',
    'config.clear': '清除 API Key',
    'config.provider.yunfan': '☁️ 云帆 AI 网关',
    'config.provider.openai': 'OpenAI',
    'config.provider.deepseek': 'DeepSeek',
    'config.provider.custom': '自定义 (OpenAI 兼容)',

    'input.label': '📝 原始内容',
    'input.chars': '字符',
    'input.placeholder': '在此粘贴你的博客文章、脚本、笔记或要点...\n\n示例：粘贴一篇完整文章、播客文字稿或你的关键要点。',
    'input.cancel': '✕ 取消',
    'input.generate': '✨ 生成多平台版本',
    'input.hint': '⚠️ 请先配置 API Key 即可生成',

    'platform.label': '📤 发布到',
    'platform.selectAll': '全选',
    'platform.none': '清空',

    'tone.label': '🎭 语气',

    'output.title': '📋 适配版本',
    'output.progress': '⏳ {done}/{total} 个平台',
    'output.download': '⬇ 下载全部 (.md)',
    'output.waiting': '等待中...',
    'output.error': '错误：',
    'output.copied': '✓ 已复制！',
    'output.copy': '📋 复制',
    'output.regenerate': '🔄 重新生成',
    'output.tweets': '条推文',
    'output.chars': '字符',

    'export.title': '# 一篇多发 — MultiPost 导出',
    'export.generated': '由一篇多发 (MultiPost) 生成',
    'export.filename': '一篇多发-导出',

    'footer.github': 'GitHub',
    'footer.contact': '联系',

    // Tones
    'tone.professional': '专业',
    'tone.casual': '随和',
    'tone.promotional': '促销',
    'tone.storytelling': '讲故事',
    'tone.educational': '教育',

    // Platform labels
    'platform.twitter': 'X / Twitter',
    'platform.linkedin': 'LinkedIn',
    'platform.newsletter': 'Newsletter',
    'platform.wechat': '微信公众平台',
    'platform.xiaohongshu': '小红书',
    'platform.reddit': 'Reddit',

    // Platform descriptions
    'platform.twitter.desc': '推文串格式，吸引眼球的开头',
    'platform.linkedin.desc': '专业调性，叙事风格',
    'platform.newsletter.desc': '完整文章，含主题行',
    'platform.wechat.desc': '中文长文，正式教育调性',
    'platform.xiaohongshu.desc': '视觉化叙述，emoji，经验分享',
    'platform.reddit.desc': '对话风格，社区意识',
  },

  en: {
    'app.logo': 'MultiPost',
    'app.tagline': 'Write Once · Publish Everywhere',
    'app.footer': 'MultiPost — your content, your API key, your data never leaves your browser',
    'app.byok': 'BYOK · v0.1',
    'app.langBtn': '中文',

    'config.configured': 'API Key configured',
    'config.configure': 'Configure AI Provider',
    'config.provider': 'Provider',
    'config.baseUrl': 'Base URL',
    'config.model': 'Model',
    'config.apiKey': 'API Key',
    'config.clear': 'Clear API Key',
    'config.provider.yunfan': '☁️ YunFan AI Gateway',
    'config.provider.openai': 'OpenAI',
    'config.provider.deepseek': 'DeepSeek',
    'config.provider.custom': 'Custom (OpenAI-compatible)',

    'input.label': '📝 Source Content',
    'input.chars': 'chars',
    'input.placeholder': 'Paste your blog post, script, notes, or bullet points here...\n\nExample: paste a full article, a podcast transcript, or just your key points.',
    'input.cancel': '✕ Cancel',
    'input.generate': '✨ Generate Platform Versions',
    'input.hint': '⚠️ Configure your API Key above to enable generation',

    'platform.label': '📤 Publish to',
    'platform.selectAll': 'Select All',
    'platform.none': 'None',

    'tone.label': '🎭 Tone',

    'output.title': '📋 Adapted Versions',
    'output.progress': '⏳ {done}/{total} platforms',
    'output.download': '⬇ Download All (.md)',
    'output.waiting': 'Waiting...',
    'output.error': 'Error: ',
    'output.copied': '✓ Copied!',
    'output.copy': '📋 Copy',
    'output.regenerate': '🔄 Regenerate',
    'output.tweets': 'tweets',
    'output.chars': 'chars',

    'export.title': '# 一篇多发 — MultiPost Export',
    'export.generated': 'Generated by 一篇多发 (MultiPost)',
    'export.filename': 'multipost-export',

    'footer.github': 'GitHub',
    'footer.contact': 'Contact',

    // Tones
    'tone.professional': 'Professional',
    'tone.casual': 'Casual / Friendly',
    'tone.promotional': 'Promotional / Sales',
    'tone.storytelling': 'Storytelling',
    'tone.educational': 'Educational',

    // Platform labels
    'platform.twitter': 'X / Twitter',
    'platform.linkedin': 'LinkedIn',
    'platform.newsletter': 'Newsletter',
    'platform.wechat': '微信公众平台',
    'platform.xiaohongshu': '小红书',
    'platform.reddit': 'Reddit',

    // Platform descriptions
    'platform.twitter.desc': 'Thread format, punchy hook',
    'platform.linkedin.desc': 'Professional tone, narrative',
    'platform.newsletter.desc': 'Full article with subject line',
    'platform.wechat.desc': '中文长文，正式教育调性',
    'platform.xiaohongshu.desc': '视觉化叙述，emoji，经验分享',
    'platform.reddit.desc': 'Conversational, community-aware',
  },
};

export const LANG_KEY = 'yuzhiran-lang';

export function getStoredLang(): Lang {
  try {
    const stored = localStorage.getItem(LANG_KEY);
    if (stored === 'en' || stored === 'zh') return stored;
  } catch { /* ignore */ }
  return 'zh';
}

export function storeLang(lang: Lang): void {
  try { localStorage.setItem(LANG_KEY, lang); } catch { /* ignore */ }
}

export function t(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  let text = translations[lang]?.[key] ?? translations['zh']?.[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replace(`{${k}}`, String(v));
    }
  }
  return text;
}

export interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const LangContext = createContext<LangContextValue>({
  lang: 'zh',
  setLang: () => {},
});

export function useLang() {
  return useContext(LangContext);
}
